apiVersion: apps/v1
kind: Deployment
metadata:
  name: ip2-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ip2-frontend
  template:
    metadata:
      labels:
        app: ip2-frontend
    spec:
      containers:
        - name: frontend
          image: snngure/ip2-client:latest
          ports:
            - containerPort: 80
          env:
            - name: REACT_APP_API_URL
              value: "http://backend-service:5000"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: LoadBalancer
  selector:
    app: ip2-frontend
  ports:
    - port: 80
      targetPort: 80
