# frontend-config.yaml
apiVersion: v1
kind: Secret
metadata:
  name: frontend-config
type: Opaque
stringData:
  REACT_APP_BACKEND_URL: "http://ip2-backend:5000"

---
# mongodb-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
stringData:
  MONGODB_URI: "mongodb+srv://<username>:<password>@<cluster-url>/<dbname>?retryWrites=true&w=majority"
