#SPDX-License-Identifier: MIT-0
---
# docker-setup role 
- name: Update the package index on the VM
  apt:
    update_cache: yes

- name: Install pre-requisite packages
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
    state: present

- name: Install python3-pip (required for docker Python SDK)
  ansible.builtin.apt:
    name: python3-pip
    state: present
  become: yes

- name: Install Docker Python SDK
  ansible
